# Generated by Django 5.2.4 on 2025-07-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restarunts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_name', models.CharField(max_length=100)),
                ('Food_cat', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('img', models.URLField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7KBKxKUEmumbhS_sR7eCr-s1likOF0RHtOvAbPXSA70O1ATMHQwZxbCCNwCYCtGQjTVo&usqp=CAU')),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
